// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// symadj
NumericMatrix symadj(NumericVector Eg, size_t n);
RcppExport SEXP _scoredec_symadj(SEXP EgSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Eg(EgSEXP);
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(symadj(Eg, n));
    return rcpp_result_gen;
END_RCPP
}
// sum_W_Wt_graph
void sum_W_Wt_graph(NumericMatrix W);
RcppExport SEXP _scoredec_sum_W_Wt_graph(SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    sum_W_Wt_graph(W);
    return R_NilValue;
END_RCPP
}
// sum_W_Wt
NumericMatrix sum_W_Wt(NumericMatrix W);
RcppExport SEXP _scoredec_sum_W_Wt(SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(sum_W_Wt(W));
    return rcpp_result_gen;
END_RCPP
}
// score_out
IntegerVector score_out(NumericMatrix W, NumericVector str_tmp);
RcppExport SEXP _scoredec_score_out(SEXP WSEXP, SEXP str_tmpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type str_tmp(str_tmpSEXP);
    rcpp_result_gen = Rcpp::wrap(score_out(W, str_tmp));
    return rcpp_result_gen;
END_RCPP
}
// score_in
IntegerVector score_in(NumericMatrix W, NumericVector str_tmp);
RcppExport SEXP _scoredec_score_in(SEXP WSEXP, SEXP str_tmpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type str_tmp(str_tmpSEXP);
    rcpp_result_gen = Rcpp::wrap(score_in(W, str_tmp));
    return rcpp_result_gen;
END_RCPP
}
// symadj_int
IntegerMatrix symadj_int(IntegerVector Eg, size_t n);
RcppExport SEXP _scoredec_symadj_int(SEXP EgSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type Eg(EgSEXP);
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(symadj_int(Eg, n));
    return rcpp_result_gen;
END_RCPP
}
// sum_W_Wt_graph_int
void sum_W_Wt_graph_int(IntegerMatrix W);
RcppExport SEXP _scoredec_sum_W_Wt_graph_int(SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type W(WSEXP);
    sum_W_Wt_graph_int(W);
    return R_NilValue;
END_RCPP
}
// sum_W_Wt_int
IntegerMatrix sum_W_Wt_int(IntegerMatrix W);
RcppExport SEXP _scoredec_sum_W_Wt_int(SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(sum_W_Wt_int(W));
    return rcpp_result_gen;
END_RCPP
}
// score_out_int
IntegerVector score_out_int(IntegerMatrix W, IntegerVector str_tmp);
RcppExport SEXP _scoredec_score_out_int(SEXP WSEXP, SEXP str_tmpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type str_tmp(str_tmpSEXP);
    rcpp_result_gen = Rcpp::wrap(score_out_int(W, str_tmp));
    return rcpp_result_gen;
END_RCPP
}
// score_in_int
IntegerVector score_in_int(IntegerMatrix W, IntegerVector str_tmp);
RcppExport SEXP _scoredec_score_in_int(SEXP WSEXP, SEXP str_tmpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type str_tmp(str_tmpSEXP);
    rcpp_result_gen = Rcpp::wrap(score_in_int(W, str_tmp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scoredec_symadj", (DL_FUNC) &_scoredec_symadj, 2},
    {"_scoredec_sum_W_Wt_graph", (DL_FUNC) &_scoredec_sum_W_Wt_graph, 1},
    {"_scoredec_sum_W_Wt", (DL_FUNC) &_scoredec_sum_W_Wt, 1},
    {"_scoredec_score_out", (DL_FUNC) &_scoredec_score_out, 2},
    {"_scoredec_score_in", (DL_FUNC) &_scoredec_score_in, 2},
    {"_scoredec_symadj_int", (DL_FUNC) &_scoredec_symadj_int, 2},
    {"_scoredec_sum_W_Wt_graph_int", (DL_FUNC) &_scoredec_sum_W_Wt_graph_int, 1},
    {"_scoredec_sum_W_Wt_int", (DL_FUNC) &_scoredec_sum_W_Wt_int, 1},
    {"_scoredec_score_out_int", (DL_FUNC) &_scoredec_score_out_int, 2},
    {"_scoredec_score_in_int", (DL_FUNC) &_scoredec_score_in_int, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_scoredec(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
