# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

symadj <- function(Eg, n) {
    .Call(`_scoreR_symadj`, Eg, n)
}

sum_W_Wt <- function(W) {
    invisible(.Call(`_scoreR_sum_W_Wt`, W))
}

score_out <- function(W, str_tmp) {
    .Call(`_scoreR_score_out`, W, str_tmp)
}

score_in <- function(W, str_tmp) {
    .Call(`_scoreR_score_in`, W, str_tmp)
}

